version: "1"

tasks:
  planner:
    prompt-string: |
      # Planner Agent Prompt

      Note that whatever task file you create - it must be small enough to fit into a single agents context window of about 100k tokens.

      1. Review Improvement Opportunities
         - Examine swarm/PLAN.md and the swarm/done/ files and the codebase for potential improvements, such as a new feature.

      2. If No Improvements Are Found
         - Propose an original, highly useful feature for agents working on the project.

      3. Write a Feature Plan
         - Plan the improvement or feature and save the tasks to {SWARM_STATE_DIR}/{YYYY-MM-DD-HH-MM-SS}-{task-name}.plan.md
         - Make sure the tasks are small enough to fit into a single agents context window of about 100k tokens.
         - You may need to break down the feature into smaller tasks and create multiple task files if it is too large. Or if it is a relatively small feature, you can just write the task in a single file.

      4. Exit Criteria
         - Exit immediately after writing one feature plan or if no improvements can be identified.

  coder:
    prompt-string: |
      # Task Workflow for the Coder Agent

      1. **Resume Unfinished Work**
         - Check for your own unfinished tasks: look for files matching `{SWARM_STATE_DIR}/*.{SWARM_TASK_ID}.processing.md`.
         - If you find such a task, skip ahead to "Implement the Task".

      2. **Claim a Todo Task**
         - Search `{SWARM_STATE_DIR}/` for files ending in `.todo.md`.
         - Choose a task that has no unresolved dependencies and won't conflict with any ongoing work.
         - Claim it by renaming it to `. {SWARM_TASK_ID}.processing.md`.
         - If no suitable todo tasks are available, skip to "If Nothing To Do".

      3. **Implement the Task**
         - Read your assigned task file and complete its requirements.
         - Add or update tests as needed, and validate your changes.
         - Once finished, rename the file to `.done.md` and move to `swarm/done/` and note your work.
         - If you are unable to finish, rename it back to `.todo.md` and briefly describe the problem encountered.

    depends_on: [planner]

  tester:
    prompt-string: |
      # Tester Agent Prompt

      Check swarm/PLAN.md for the project plan. Also check SWARM_STATE_DIR for what has been done in the current iteration.
      Focus on testing just the work done in the current iteration.

      ## 1. Run Unit Tests

      Fix any issues you find

      ## 2. Build and test in a browser - mobile and desktop viewports need to be tested.

      Fix any issues you find

    depends_on: [coder]

  checker:
    prompt-string: |
      # Review unstaged git changes for bugs

      Run `git diff` to see all unstaged changes in the repository.

      # Analyze the changes for bugs

      Carefully review the diff output and look for bugs such as:
      - Off-by-one errors or incorrect boundary conditions
      - Null/undefined access without proper guards
      - Race conditions or missing awaits on async calls
      - Incorrect logic (wrong operator, inverted condition, swapped arguments)
      - Unhandled error cases or missing try/catch blocks
      - Security issues (unsanitized input, exposed secrets, injection vectors)
      - State management bugs (stale closures, missing dependency arrays, mutation of shared state)
      - Type mismatches or unsafe casts that could cause runtime errors

      # Fix bugs

      If you find bugs, fix them directly in the code.
      Keep fixes minimal and targeted — only fix actual bugs, don't refactor or add features.
      Make sure the code still compiles and any relevant tests still pass after your fixes.

      # Finally

      If the unstaged changes look correct, git commit and push and then exit immediately.

    depends_on: [tester]

pipelines:
  development:
    iterations: 100
    parallelism: 5
    tasks: [planner, coder, tester, checker]
